apiVersion: apps/v1
kind: Deployment
metadata:
  name: swish-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swish-app
  template:
    metadata:
      labels:
        app: swish-app
    spec:
      containers:
      - name: keen-benz
        image: swish:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"  
            memory: "512Mi"  
          requests:
            cpu: "0.1"       
            memory: "256Mi"  # Minimum memory requested by the container
        readinessProbe:
          httpGet:
            path: /health 
            port: 80   
         initialDelaySeconds: 10   
          periodSeconds: 30         # Check readiness every 30 seconds
        livenessProbe:
          httpGet:
            path: /healthz  
            port: 80        
          initialDelaySeconds: 15   
          periodSeconds: 60         # Check liveness every 60 seconds
        # Logging configuration
        env:
          - name: LOG_LEVEL
            value: "info"   # Set logging level
          - name: LOG_FORMAT
            value: "json"   # Set logging format
