apiVersion: v1
kind: Service
metadata:
  name: swish-service   # Name of your Service
spec:
  selector:
    app: swish-app      # Selector to match pods with label 'app: swish-app'
  ports:
    - protocol: TCP
      port: 80           # Port on the Service
      targetPort: 80     # Port on the pods (containerPort in Deployment)
  type: ClusterIP        # Type of Service (ClusterIP, NodePort, LoadBalancer)
